In [1]:
import numpy as np 
from matplotlib import pyplot as plt 
from scipy.special import factorial
import math
from tqdm import tqdm
import sympy as sp
import copy 

In [2]:
#x = np.arange(-10, 10, 1)

In [3]:
x = np.linspace(-10, 10, 22)

In [4]:
x

array([-10.        ,  -9.04761905,  -8.0952381 ,  -7.14285714,
        -6.19047619,  -5.23809524,  -4.28571429,  -3.33333333,
        -2.38095238,  -1.42857143,  -0.47619048,   0.47619048,
         1.42857143,   2.38095238,   3.33333333,   4.28571429,
         5.23809524,   6.19047619,   7.14285714,   8.0952381 ,
         9.04761905,  10.        ])

In [5]:
def hermite(x, k):
    if k == 0:
        return 1
    elif k == 1:
        return 2 * x
    else:
        return 2 * x * hermite(x, k - 1) - 2 * (k - 1) * hermite(x, k - 2)

In [6]:
l = np.arange(len(x), 0, -1) * 1.0
ck = np.zeros_like(l)

for k in range(len(l)):
    ck[k] = (np.sqrt(np.pi) * (2 ** k) * factorial(k))**(-0.5)

In [7]:
ck.shape

(22,)

In [8]:
B = []

for ki in tqdm(range(len(x))):
    temp = ck[ki] * np.exp(-x * x/2) * hermite(x, ki)
    B.append(temp)

B = np.array(B)


100%|███████████████████████████████████████████| 22/22 [00:00<00:00, 86.12it/s]


In [9]:
B.shape

(22, 22)

In [10]:
BB = copy.deepcopy(B)

In [11]:
B = B[:20]

In [12]:
B.shape

(20, 22)

In [13]:
BB.shape

(22, 22)

In [14]:
# V is diagonal matrix 
V = np.diag(x[:-2])

In [15]:
V.shape

(20, 20)

In [16]:
B.shape

(20, 22)

In [17]:
(V@B).shape

(20, 22)

In [19]:
w = 3000

In [20]:
b_n = []
for i in tqdm(range(20)):
    n = i
    
    second_derivative = (0.5 * np.sqrt((n+1) * (n+2)) * BB[n+2]
                         + np.sqrt(n * (n-1)) * BB[n-2]
                         - (2*n+1) * BB[n])
    
    b_n.append(second_derivative)

# Calculate |K''|
K = (-w/2) * np.array(b_n)

100%|████████████████████████████████████████| 20/20 [00:00<00:00, 23810.98it/s]


In [21]:
K.shape

(20, 22)

In [33]:
V@B + K

array([[-2.14064829e-17, -1.51820857e-13, -4.24588272e-10,
        -4.65270593e-07, -1.97912922e-04, -3.21986520e-02,
        -1.95255589e+00, -4.18920302e+01, -2.76394467e+02,
        -2.22339584e+02,  1.27407589e+03,  1.27407589e+03,
        -2.22339584e+02, -2.76394467e+02, -4.18920302e+01,
        -1.95255589e+00, -3.21986520e-02, -1.97912922e-04,
        -4.65270593e-07, -4.24588272e-10, -1.51820857e-13,
        -2.14064829e-17],
       [ 2.93511752e-16,  1.87005761e-12,  4.63309443e-09,
         4.41519319e-06,  1.59149008e-03,  2.10934168e-01,
         9.72983629e+00,  1.35869170e+02,  2.61879416e+02,
        -2.01273945e+03, -2.89070559e+03,  2.89070559e+03,
         2.01273945e+03, -2.61879416e+02, -1.35869170e+02,
        -9.72983629e+00, -2.10934168e-01, -1.59149008e-03,
        -4.41519319e-06, -4.63309443e-09, -1.87005761e-12,
        -2.93511752e-16],
       [-2.82884034e-15, -1.61653386e-11, -3.53948248e-08,
        -2.92206805e-05, -8.86483452e-03, -9.43768570e-01,
    

In [23]:
(V@B + K).shape

(20, 22)

In [24]:
B.T.shape

(22, 20)

In [29]:
H = B@(V@B + K).T

In [30]:
H.shape

(20, 20)

In [31]:
H

array([[ 1.56379650e+03,  3.52209309e-12, -2.21282891e+03,
        -4.57134587e-12, -1.17002871e+02, -3.98257411e-12,
         5.74761142e+02,  2.10536336e-11, -2.01534844e+03,
        -3.52395046e-11,  5.46776711e+03,  4.12644585e-11,
        -1.20625196e+04, -2.75215249e-11,  2.23804281e+04,
        -5.91728033e-12, -3.57832479e+04,  5.33104809e-11,
         5.02195343e+04, -1.01235139e-10],
       [ 4.68777486e-13,  4.73127809e+03,  4.99781174e-12,
        -4.02604870e+03, -2.15806950e-11,  9.27747796e+02,
         3.37466632e-11, -3.37705156e+03, -2.83000964e-11,
         9.00974707e+03, -4.53392293e-12, -1.86478611e+04,
         6.48150753e-11,  3.08918304e+04, -1.33811797e-10,
        -4.14451808e+04,  1.79757387e-10,  4.44560145e+04,
        -1.67576763e-10, -3.55027588e+04],
       [-1.10464885e+03,  3.60946477e-12,  7.70731657e+03,
        -1.03566363e-11, -4.40363814e+03,  9.57567065e-12,
        -4.10709041e+03,  9.86994094e-12,  1.09754941e+04,
        -5.22789135e-11, -2.1

In [ ]:
#w = 3000
#β = 200